### ISSUE TITLE
Pip install is not working for me, which python version are you using?

### ISSUE THREAD

**Issue by kwisser** [neerajram30/Final-year-project#1]
Im getting this error if I do "pip install -r -requirements.txt":

```
The conflict is caused by:
    The user requested opencv-python
    The user requested opencv-python==4.4.0.46

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

Also if i try to install it line by line im getting an error

**Comment by neerajram30** [comment]
I am using python 3.9, Thanks for helping out I will make changes to requiremets.txt accordingly.

**Comment by kwisser** [comment]
Okay cool thank you, I also tried it with python3.9 on Debian, Ubuntu and Arch and always got Errors during pip install -r requirements.txt

**Comment by neerajram30** [comment]
requiremets.txt file updated solved dependency conflict problem.
